import assert from "node:assert/strict";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, it } from "node:test";
import { runCli } from "./cli.js";
import { SUGGESTION } from "./migration.js";
import { createFixture, removeFixture } from "../test/fixtures.js";
import { commitAll, git } from "../test/git.js";
import { fakeIo } from "../test/io.js";
import { SAMPLE_PROJECT } from "../test/sample.js";

/** Run the CLI on a directory, returning the io. */
async function cli(args) {
  const io = fakeIo();
  io.code = await runCli(args, io);
  return io;
}

describe("--fix", () => {
  it("writes migration.patch that git apply accepts", async () => {
    const dir = await createFixture(SAMPLE_PROJECT);
    try {
      await commitAll(dir);
      const io = await cli([dir, "--fix"]);
      assert.equal(io.code, 0, io.err);
      assert.ok(io.out.includes("\nAutomatic fixes\n"));
      assert.ok(
        io.out.includes(`Wrote ${join(dir, "migration.patch")} (7 files).`),
      );
      const patch = await readFile(join(dir, "migration.patch"), "latin1");
      assert.match(
        patch,
        /^# migration\.patch: generated by xslt-migrate-check \d+\.\d+\.\d+\n/,
      );
      assert.ok(patch.includes(`+    ${SUGGESTION.script}\n`));
      assert.ok(
        patch.includes('+require("@tradik/xslt-processor/polyfill");\r\n'),
      );
      const check = await git(dir, "apply", "--check", "migration.patch");
      assert.equal(check.code, 0, check.stderr);
      // Nothing was changed in place
      assert.equal(
        (await git(dir, "status", "--porcelain")).stdout,
        "?? migration.patch\n",
      );
    } finally {
      await removeFixture(dir);
    }
  });

  it("--write needs a clean tree, then changes the files; the rescan sees them migrated", async () => {
    const dir = await createFixture(SAMPLE_PROJECT);
    try {
      await commitAll(dir);
      await writeFile(join(dir, "notes.txt"), "dirty");
      const dirty = await cli([dir, "--fix", "--write"]);
      assert.equal(dirty.code, 2);
      assert.match(dirty.err, /--write needs a clean git working tree/);
      const forced = await cli([dir, "--fix", "--write", "--force", "--json"]);
      assert.equal(forced.code, 0, forced.err);
      assert.ok(forced.err.includes("Changed 7 files in place."));
      JSON.parse(forced.out);
      const legacy = await readFile(join(dir, "src/legacy.js"), "latin1");
      assert.ok(
        legacy.startsWith(
          '"use strict";\r\nrequire("@tradik/xslt-processor/polyfill");\r\n',
        ),
      );
      const rescan = JSON.parse((await cli([dir, "--json"])).out);
      assert.deepEqual(rescan.usages, []);
      assert.deepEqual(rescan.xmlDocuments, []);
      assert.deepEqual(rescan.migrated.map((m) => m.file).sort(), [
        "public/catalog.xml",
        "public/index.html",
        "public/invoice.xml",
        "public/orders.xml",
        "src/legacy.js",
        "src/report.js",
      ]);
      assert.ok(rescan.findings.every((f) => f.rating !== "HIGH"));
      assert.ok(!rescan.recommendations.some((r) => r.id === "server"));
      const again = await cli([dir, "--fix"]);
      assert.ok(again.out.includes("Nothing to change automatically."));
    } finally {
      await removeFixture(dir);
    }
  });

  it("--write runs outside git, and reports a file it cannot write", async () => {
    const dir = await createFixture({ "a.mjs": "new XSLTProcessor();\n" });
    try {
      const io = await cli([dir, "--fix", "--write"]);
      assert.equal(io.code, 0, io.err);
      await mkdir(join(dir, "b"));
      await writeFile(join(dir, "b.mjs"), "new XSLTProcessor();\n");
      await mkdir(join(dir, "migration.patch"));
      const failed = await cli([dir, "--fix"]);
      assert.equal(failed.code, 2);
      assert.match(failed.err, /^Error: cannot write .*migration\.patch: /);
    } finally {
      await removeFixture(dir);
    }
  });

  it("lists what it leaves to the user", async () => {
    const dir = await createFixture({ "a.js": "new XSLTProcessor();\n" });
    try {
      const io = await cli([dir, "--fix"]);
      assert.ok(io.out.includes("\nLeft to you:\n  a.js  not a module;"));
    } finally {
      await removeFixture(dir);
    }
  });

  it("rejects --write without --fix and --force without --write", async () => {
    assert.match((await cli(["--write"])).err, /--write needs --fix/);
    assert.match(
      (await cli(["--fix", "--force"])).err,
      /--force needs --write/,
    );
  });
});
