import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        global: 'readonly',
        globalThis: 'readonly',
        process: 'readonly',
        document: 'readonly',
        DOMParser: 'readonly',
        XMLSerializer: 'readonly',
        NodeFilter: 'readonly'
      }
    },
    rules: {
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-console': 'off',
      'prefer-const': 'error',
      'no-var': 'error',
      'eqeqeq': ['error', 'always', { null: 'ignore' }],
      'curly': ['error', 'multi-line'],
      'no-throw-literal': 'error'
    }
  },
  {
    files: ['**/*.test.js'],
    languageOptions: {
      globals: {
        describe: 'readonly',
        it: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        before: 'readonly',
        after: 'readonly'
      }
    }
  },
  {
    // Playwright specs run in Node; page.evaluate callbacks and the fixtures
    // run in the browser page
    files: ['tests/browser/**/*.mjs'],
    languageOptions: {
      globals: {
        window: 'readonly',
        location: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Node: 'readonly',
        Document: 'readonly',
        DocumentFragment: 'readonly',
        HTMLElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLParagraphElement: 'readonly'
      }
    }
  },
  {
    // Project website: browser scripts of the theme
    files: ['site/templates/**/js/*.js'],
    languageOptions: {
      globals: {
        window: 'readonly',
        performance: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        Option: 'readonly',
        history: 'readonly',
        location: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly'
      }
    }
  },
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'coverage/**',
      'test-results/**',
      // Generated by site/scripts/build-content.mjs and ssg
      'site/content/**',
      'site/data/**',
      'site/static/vendor/**',
      'site/static/assets/**',
      'site/public/**',
      'site/public-local/**'
    ]
  }
];
