/**
 * The console text of `--fix`: the files that change and how, the files
 * left to the user, and where the patch went. Pure.
 *
 * @module xslt-migrate-check/fix/summary
 */

import { pluralize } from "../format.js";

/** The patch file name, written into the scanned directory. */
export const PATCH_FILE = "migration.patch";

/**
 * The header lines of the patch: tool, version and what it does.
 *
 * @param {import("../analysis/index.js").Analysis} analysis - The analysis
 * @param {import("./plan.js").FixPlan} plan - The plan
 * @returns {string[]} Lines without the `# ` prefix
 */
export function patchHeader(analysis, plan) {
  const { summary } = analysis;
  return [
    `${PATCH_FILE}: generated by xslt-migrate-check ${analysis.version}`,
    `Risk ${analysis.risk}; ${pluralize(summary.findings, "finding")}, ${summary.automatic} compatible automatically, ${summary.manualReview} for manual review.`,
    `Runtime: ${summary.recommendedRuntime}. Changes ${pluralize(plan.edits.length, "file")}; stylesheets are never changed.`,
    "Review it, then run: git apply migration.patch",
  ];
}

/**
 * Lay out path/text rows in two columns.
 *
 * @param {Array<[string, string]>} rows - Path and text
 * @returns {string[]} Indented lines
 */
function columns(rows) {
  const width = Math.max(...rows.map(([path]) => path.length));
  return rows.map(([path, text]) => `  ${path.padEnd(width)}  ${text}`);
}

/**
 * The console lines of `--fix`.
 *
 * @param {import("./plan.js").FixPlan} plan - The plan
 * @param {{target: string, write: boolean}} outcome - The patch path, and
 *   whether the files were changed in place instead
 * @param {{bold: Function}} style - Text decorators
 * @returns {string[]} Lines, starting with a blank one
 */
export function fixLines(plan, { target, write }, style) {
  const lines = ["", style.bold("Automatic fixes")];
  if (plan.edits.length === 0) {
    lines.push("", "  Nothing to change automatically.");
  } else {
    lines.push("", ...columns(plan.edits.map((e) => [e.path, e.change])));
  }
  if (plan.skipped.length > 0) {
    lines.push(
      "",
      "Left to you:",
      ...columns(plan.skipped.map((s) => [s.path, s.reason])),
    );
  }
  if (plan.edits.length > 0) {
    const files = pluralize(plan.edits.length, "file");
    lines.push(
      "",
      write
        ? `Changed ${files} in place. Run xslt-migrate-check again to see them migrated.`
        : `Wrote ${target} (${files}). Review it, then: git apply ${PATCH_FILE}`,
    );
  }
  return lines;
}
